
steps:
- name: 'hashicorp/terraform:0.14.8'
  id: 'rj-init'
  entrypoint: 'sh'
  args: ['-c', 'terraform init']

- name: 'hashicorp/terraform:0.14.8'
  id: 'rj-validate'
  entrypoint: 'sh'
  args: ['-c', 'terraform validate']

- name: 'hashicorp/terraform:0.14.8'
  id: 'rj-plan'
  entrypoint: 'sh'
  args: ['-c', 'terraform plan']

- name: 'hashicorp/terraform:0.14.8'
  id: 'rj-apply'
  entrypoint: 'sh'
  args: ['-c', 'terraform apply --auto-approve -var="project_id=${_PROJECT_ID}" -var="region=${_REGION}" -var="zone=${_ZONE}" -var="db_password=$$DB_PASSWORD"']
  secretEnv: ['DB_PASSWORD']

availableSecrets:
  secretManager:
  - versionName: projects/682035886856/secrets/rj/versions/1
    env: 'DB_PASSWORD'
substitutions:
  _PROJECT_ID: "burner-ravk"
  _REGION: "us-central1"	
  _ZONE: "us-central1-a"
timeout: 1800s